### ISSUE TITLE
stridedpointer_preserve no longer in VectorizationBase

### ISSUE THREAD

**Issue by gzheng92** [JuliaSIMD/TriangularSolve.jl#11]
In the latest codebase, https://github.com/JuliaSIMD/TriangularSolve.jl/blob/50b01ecb2b49c91137a1922c8875dcc995ceefc8/src/TriangularSolve.jl#L4 the module imports stridedpointer_preserve from VectorizationBase, which does not seem to include this function anymore.  Instead, it looks like it should be imported either directly from LayoutPointers or from LoopVectorization

I tried the latter approach and got an error
```
[ Info: Precompiling TriangularSolve [d5829a12-d9aa-46ab-831f-fb7c9ab06edf]
ERROR: LoadError: MethodError: no method matching (LayoutPointers.StridedPointer{Float64, 2, 1, 0, (1, 2), X, O} where {X, O})(::Ptr{Float64}, ::Tuple{Static.StaticInt{8}, Static.StaticInt{96}}, ::Tuple{Static.StaticInt{0}, Static.StaticInt{0}})
```

**Comment by chriselrod** [comment]
Thanks for the issue and reminder to fix this.
Tests passed locally with https://github.com/JuliaSIMD/TriangularSolve.jl/commit/7ccf7606689392a1dc13ebba7ff4e8ef150be099, so I'll tag a new release once they pass.
