### ISSUE TITLE
Segfault on julia 1.6.5

### ISSUE THREAD

**Issue by j-fu** [JuliaSIMD/TriangularSolve.jl#18]
Hi, I am getting a segfault on Julia 1.6.5 when `using TriangularSolve`:
https://gist.github.com/j-fu/03d66b7a48a592516c14001f3f132113

This doesn't happen neither with 1.6.4, nor with 1.7.0.

**Comment by chriselrod** [comment]
Interesting. 
Can you try ThreadingUtilities.jl?
