### ISSUE TITLE
`ldiv!` invokes undefined behavior when calling `m_thread_block_size` with `nthreads == static(0)`.

### ISSUE THREAD

**Issue by KristofferC** [JuliaSIMD/TriangularSolve.jl#26]
https://github.com/JuliaSIMD/TriangularSolve.jl/blob/e425ff59ceba9711e904d6b1584dacfd5fdc8292/src/TriangularSolve.jl#L264 and many more places ends up calling `m_thread_block_size` with `nthreads == static(0)`.

The compiler can then prove that

https://github.com/JuliaSIMD/TriangularSolve.jl/blob/e425ff59ceba9711e904d6b1584dacfd5fdc8292/src/TriangularSolve.jl#L335

is called as `VectorizationBase.vcld(M, 0)` (which ends up calling `Base.sdiv_int(x, 0)` which is undefined behavior https://llvm.org/docs/LangRef.html#sdiv-instruction) and returns llvm's `poison` value.

Maybe this should just have been `static(1)`?

**Comment by chriselrod** [comment]
Yeah, definitely looks like it should have been `1`.
